name: CI

on:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}

    steps:
    - uses: JCofman/vscodeaction@v0.1-alpha
    - name: Vscode release plugin
